name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend:
    name: Validar backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      DATABASE_URL: postgresql://ci:ci@localhost:5432/financehub?schema=public

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Compilar backend
        run: npm run build

  frontend:
    name: Validar frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    env:
      NEXT_PUBLIC_API_URL: https://financehub-api-ry31.onrender.com

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Compilar frontend
        run: npm run build